CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE refresh_token (
                               id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               token VARCHAR(255) NOT NULL UNIQUE,
                               expiry_date TIMESTAMPTZ NOT NULL,
                               user_id BIGINT UNIQUE,
                               CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE resume (
                        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        full_name VARCHAR(255),
                        age INT,
                        experience TEXT,
                        skills TEXT,
                        education TEXT,
                        user_id BIGINT,
                        CONSTRAINT fk_resume_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE job_vacancies (
                               id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               title VARCHAR(255),
                               description TEXT,
                               company_name VARCHAR(255),
                               employer_id BIGINT,
                               CONSTRAINT fk_vacancy_employer FOREIGN KEY (employer_id) REFERENCES users(id)
);

CREATE TABLE application (
                             id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             status VARCHAR(255) CHECK (status IN ('NEW','REVIEWED','ACCEPTED','REJECTED')),
                             resume_id BIGINT,
                             vacancy_id BIGINT,
                             CONSTRAINT fk_application_resume FOREIGN KEY (resume_id) REFERENCES resume(id),
                             CONSTRAINT fk_application_vacancy FOREIGN KEY (vacancy_id) REFERENCES job_vacancies(id)
);
